### ISSUE TITLE
Identify Functional Requirements

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#1]
**Admin Staff:**
- A Manager shall be able to view the staff workload on the landing page
- A Manager shall be able to allocate jobs to employees for one week at a time
- A Manager shall be able to view up to three staff availability and any relevant information to make the job assignment easier on the job allocation page
- A Manager shall be able to Manage jobs assigned to Staffs
- A Manager shall be able to view Employees with the >40hours workload for the week
- A manager shall be able to view the Employees with the least hours for the week on the landing page

**Employee**
- An **employee** shall be able to view assigned working hours
- An **employee** shall be able to upload their availabilities up to 1 month prior.
     Weekly cut-off dates for submission will be Wednesdays
- An **employee** shall be able to indicate their job preferences for the week
- An **employee** shall be able to reject jobs assigned to them

**IT Administrator**
- An IT Administrator should be able to add new user accounts to the system
- An IT Administrator should be able to remove and edit user accounts on the system
- An IT Administrator should be able to reset password for staff and manager accounts in the system

**Comment by mingwei1744** [comment]
- A Manager shall be able to view the staff workload on the landing page
- A Manager shall be able to allocate jobs to employees for one week at a time
- A Manager shall be able to view up to three staff availability and any relevant information to make the job assignment easier on the job allocation page

**Comment by FadedCopy** [comment]
A Manager shall be able to Manage Job Allocation 
A Manager shall be able to view Employees with the >40hours workload for the week 
A manager shall be able to view the Employees with the least hours for the week on the landing page

**Comment by SeanT99** [comment]
- An **employee** shall be able to view assigned working hours
- An **employee** shall be able to upload their availabilities up to 1 month prior.
     Weekly cut-off dates for submission will be Wednesdays
- An **employee** shall be able to indicate their job preferences for the week
- An **employee** shall be able to reject jobs assigned to them

**Comment by SeanT99** [comment]
- An **IT Administrator** should be able to add new user accounts to the system
- An **IT Administrator** should be able to remove and edit user accounts on the system
- An **IT Administrator** should be able to reset password for all users of the system

**Comment by SeanT99** [comment]
Requirements have been gathered as per task description
