### ISSUE TITLE
DUE 25/10 - Revise ALL Use Case Descriptions

### ISSUE THREAD

**Issue by mingwei1744** [ict2201P7G1Project/ICT2201_P7-1#25]
Post-M1 Submission Review
- Review all use cases without alt scenarios or post-conditions
- Missing STAFF use case for late request?
- All other UC

Highlighted UC:
UC-AMP-001
UC-AMP-002
UC-AMP-004

**Comment by FadedCopy** [comment]
Reviewed AMP use case

**Comment by SeanT99** [comment]
Assigned to:
Sean/ Scott - AMP-xx
Ming Wei - ITA-xx
Virence - EMP-xx

**Comment by SeanT99** [comment]
Added alternative scenarios for UC-AMP-002
Made changes to UC-AMP-004

**Comment by mingwei1744** [comment]
Administrative Manager Use Case updates
+ Plan Job Allocation: allows Administrative Managers to plan the workload for the upcoming week.
+ Modify Job Allocation: allows the Administrative Manager to update or delete allocated jobs.

**Comment by SeanT99** [comment]
Rewrote create staff and modify staff use cases
Changed the flow of the late request
Closing as completed the revision
