### ISSUE TITLE
DUE 25/10 - Review System Architect Diagram

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#26]
Post-m1 submission review
To review and check the flows
-> Unlikely actors will interact directly with email server

**Comment by virence1** [comment]
Initial editing based on review has been done. Chart reference : https://lucid.app/lucidchart/199e4097-55de-4eda-8ce9-3217884e08f4/edit?viewport_loc=-185%2C-18%2C2994%2C1438%2C0_0&invitationId=inv_a2d9da42-8456-40c9-8a92-4f16dba8f212
