### ISSUE TITLE
Due 28/10 - Review the references and background literature

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#27]
Post-m1 submission review
To review and see if there are any retail pharmacy industry related references

**Comment by virence1** [comment]
Initial scholarly articles found, will be included into the report if applicable:
- https://www.eijst.org.uk/images/frontImages/gallery/Vol._2_No._9/13.pdf 
- https://www.sciencedirect.com/science/article/pii/S0305054816300314?casa_token=oRQt_h9RaakAAAAA:2O4icFa7wHmfC3Qj_-oFkL-H2o9aLZ-DpgefIE-ZthET9d78UJykTT6c_AshUW4KJKwcOaLMrFLl8g
