### ISSUE TITLE
DUE 28/10 - Amend the user interface

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#29]
Post-m1 submission review:
**Admin Manager Landing Page** - "Prefer more details.
Should have days of the week showing how many hours per day for each staff. the rightmost column can have total hours worked per week."
**Workload Planning Page** - "Which shift is he/she allocating"

**Comment by mingwei1744** [comment]
Updated Admin Manager Landing Page UI with additional staff information

**Comment by mingwei1744** [comment]
Rework on Plan Job Allocation UI

**Comment by SeanT99** [comment]
To move all ui to apendix

**Comment by mingwei1744** [comment]
Updated UI to Appendix A of M2
