### ISSUE TITLE
Craft the Use Case Diagram

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#3]

**Comment by virence1** [comment]
IT Administrator UC Diagram Link : https://lucid.app/lucidchart/76b18155-6934-45a7-bb0a-644942ae7dc3/edit?viewport_loc=-309%2C72%2C3072%2C1545%2C.Q4MUjXso07N&invitationId=inv_d69b0145-1c48-4c42-94b6-4589cc88cf61#

**Comment by virence1** [comment]
Manager Diagram Link : https://lucid.app/lucidchart/a2c71f64-fa85-4fe7-a53e-ffc3fa1eaa08/edit?viewport_loc=-340%2C74%2C3201%2C1610%2C.Q4MUjXso07N&invitationId=inv_300be918-8b70-491f-bd85-281722333c4d#

**Comment by SeanT99** [comment]
Closed as delegated work in other tasks

**Comment by SeanT99** [comment]
Closed as completed on behalf of @mingwei1744
