### ISSUE TITLE
DUE 25/10 - Update functional requirements

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#31]
Post-M1 Submission Review
**Missing** - If staff meet deadline, staff should be able to inform manager of his/her availability.
**Amendment** - FR8 - Before Thursday, staff should still be allowed to amend on Wednesday

**Comment by mingwei1744** [comment]
Identify functional requirements that were overlooked from requirement elicitation

**Comment by mingwei1744** [comment]
Performance Requirement updates
+ The System shall update staff’s workload within 3 sec after jobs are allocated to them.
+ The System shall have an availability of 99%. Maintenance is done during non-working hours, 3am to 5am.

**Comment by mingwei1744** [comment]
Safety and Security Requirements updates
+ To foster secure password storage, the system shall salt and hash users’ credentials before storing them into the database.
+ Data sanitization and validation will be performed on all user inputs to prevent cross-site scripting and SQL injection. This is a preventive measure for data breach.
