### ISSUE TITLE
DUE 28/10 - Component Diagram

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#35]

**Comment by FadedCopy** [comment]
Completed 1st Draft. Pre-architecture and design pattern influence

**Comment by mingwei1744** [comment]
Grouped Class Diagram into relevant components. First draft produced

**Comment by FadedCopy** [comment]
Designed to be layered architecture deisgn

**Comment by mingwei1744** [comment]
Added layered architecture design to component diagram. Second draft produced
