### ISSUE TITLE
DUE 28/10 - Class Diagram

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#36]

**Comment by FadedCopy** [comment]
Completed with interface. Pre architecture and design pattern

**Comment by mingwei1744** [comment]
Completed first two iterations of Class Diagram

**Comment by mingwei1744** [comment]
Expanded class diagram with ECB

**Comment by FadedCopy** [comment]
Added design patterns into class diagram

**Comment by mingwei1744** [comment]
Implemented adapter design pattern to class diagram
