### ISSUE TITLE
DUE 28/10 - Sequence Diagram

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#37]
Todo:
UC-AMP-002: Plan Job Allocation - Ming Wei/Scott
UC-AMP-003: Submit Job Schedule - Ming Wei/Scott
UC-EMP-001: Submit Availability - Ming Wei/Scott
UC-EMP-002: Submit Late Requests - Sean
UC-EMP-004: Reject Assigned Jobs - Sean
UC-ITA-001: Create new staff account - Virence

**Comment by mingwei1744** [comment]
First draft of Plan Job Allocation produced. To review the sequence of interaction

**Comment by FadedCopy** [comment]
Drafted Submit Job schedule and submit availability SD

**Comment by SeanT99** [comment]
Created Draft for submit late request

**Comment by mingwei1744** [comment]
First draft of Submit Job Schedule produced. To review the sequence of interaction

**Comment by SeanT99** [comment]
Drafted and uploaded first draft of sequence diagram for UC-EMP-004

**Comment by SeanT99** [comment]
Relooked and drafted sequence diagram for UC-EMP-004 and UC-EMP-002 and uploaded to Slack

**Comment by mingwei1744** [comment]
Revise Plan Job Allocation sequence diagram alt frames

**Comment by FadedCopy** [comment]
Input of numbers to sequence

**Comment by SeanT99** [comment]
Changed numbering for UC-EMP-002 and UC-EMP-004.
Changed the alt flow portion of the diagram
