### ISSUE TITLE
Requirements Elicitation - Client Meeting 15/09

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#4]
1. How are shifts divided?
2. Does rejections have to be approved on the system?
3. What are the roles an account can have?
4. What fields are required for the job preferences and rejections?
5. How many days are staff expected to work weekly?
6. How are calendars displayed? Branch by branch? All branches share one?
7. How are 3 staff availability displayed? How are they selected?
8. What happens if staff dont indicate their availability?
9. Should staff be allowed to view everyone’s schedule or only their own?
**10. NFR: Browser? Data preservation policy? Authentication method?**
**11. Will the app be hosted on the intranet or public domain internet?**

**Comment by virence1** [comment]
- What is the duration of the training that the employee can take to be able to use the web-app without much supervision/guidance? Can we assign a 2-3 hour training session for it?

**Comment by virence1** [comment]
- What devices do the organisation mainly use for surfing the web? Do the web-app has to be designed in mind with compatibility for extremely old devices? (i.e. older iPhone versions, etc.)

**Comment by virence1** [comment]
Initial draft of meeting minutes https://docs.google.com/document/d/1hSSD2H8E1CxMBdEABAaHo1xGgjIjkkUl/edit?usp=sharing&ouid=101855220013830987398&rtpof=true&sd=true

**Comment by SeanT99** [comment]
**Post-meeting questions:**
Which role can see the manager landing page with staff workload?

**Comment by SeanT99** [comment]
Closed as meeting has been completed
