### ISSUE TITLE
Blackbox testing  - Decision Table

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#50]

**Comment by mingwei1744** [comment]
First draft of decision table established based on the state diagram

**Comment by FadedCopy** [comment]
Drafted and checked Decision tables

**Comment by mingwei1744** [comment]
Updated authenticate user decision table

**Comment by mingwei1744** [comment]
Updated submit late request decision table

**Comment by SeanT99** [comment]
updated the plan job allocation and submit job allocation decision tables

**Comment by SeanT99** [comment]
uploaded the final decision table to github  and inserted into report
