### ISSUE TITLE
Prototype - Figma

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#51]

**Comment by mingwei1744** [comment]
Prototype created for Staff submit availability

**Comment by mingwei1744** [comment]
Prototype created for Staff submit late request

**Comment by mingwei1744** [comment]
Prototype created for Staff landing page

**Comment by FadedCopy** [comment]
Branch manager view of job schedule and Staff Late request page completed

**Comment by mingwei1744** [comment]
Updated prototype for staff, reject allocated job

**Comment by mingwei1744** [comment]
Updated prototype for staff, submit availability

**Comment by mingwei1744** [comment]
Prototype completed
