### ISSUE TITLE
Prototype - Readme file

### ISSUE THREAD

**Issue by SeanT99** [ict2201P7G1Project/ICT2201_P7-1#56]

**Comment by mingwei1744** [comment]
Added readme document to project repository: https://github.com/ict2201P7G1Project/ICT2201_P7-1

**Comment by mingwei1744** [comment]
updated screenshots to show access to the prototype

**Comment by mingwei1744** [comment]
Embedded reference links to readme

**Comment by mingwei1744** [comment]
Readme completed
