### ISSUE TITLE
System’s Architecture Diagram

### ISSUE THREAD

**Issue by mingwei1744** [ict2201P7G1Project/ICT2201_P7-1#9]

**Comment by virence1** [comment]
Diagram link : https://lucid.app/lucidchart/199e4097-55de-4eda-8ce9-3217884e08f4/edit?viewport_loc=-185%2C-18%2C2994%2C1437%2C0_0&invitationId=inv_a2d9da42-8456-40c9-8a92-4f16dba8f212#

**Comment by mingwei1744** [comment]
Close as completed
